a = int(input("Insira um valor inteiro (A): "))
b = int(input("Insira outro valor inteiro (B): "))
c = float(input("Insira um valor real (C): "))
print("O produto do dobro de A com metade de B é :", (a * 2) * (b / 2))
print("A soma do triplo de A com o C é :", (a * 3) + c)
print("C elevado ao cubo é:", c ** 3)
input()
